export enum ZakahStatus {
  BELOW_NISAB = 'BELOW_NISAB',
  ELIGABLE_FOR_ZAKAH = 'ELIGABLE_FOR_ZAKAH',
  HAWL_NOT_COMPLETED = 'HAWL_NOT_COMPLETED',
  ZAKAH_DUE = 'ZAKAH_DUE',
  LAST_RECORD_DUE_AND_NEW_HAWL_BEGIN = 'LAST_RECORD_DUE_AND_NEW_HAWL_BEGIN'
}
